---
# General test suite configuration
suite: Docker Example Test Suite

# Define the docker resources that will be used. This section is only used if you have docker nodes
docker:
  # Define the network that will be used in the test suite
  networks:
    - name: test_net
      subnet: 192.168.200.0/24
      gateway: 192.168.200.1
  # Define the images that will be used in the test suite
  images:
    - name: test_server
      tag: latest
      dockerfile: dockerfiles/server.dockerfile
    - name: test_client
      tag: latest
      dockerfile: dockerfiles/client.dockerfile

# Define the nodes that will be used in the test suite
nodes:
  - name: docker-server
    type: docker
    options:
      image: test_server:latest
      exec_opts:
        shell: /bin/bash
      networks:
        - name: test_net
          ip: 192.168.200.10

  - name: docker-client
    type: docker
    options:
      image: test_client:latest
      exec_opts:
        shell: /bin/bash
      networks:
        - name: test_net
          ip: 192.168.200.100

# Define the setup steps that will be executed before the tests begin
setup:
  - name: step 1
    node: docker-client
    step:
      type: simulated
      options:
        time: 2
        message: installing fake package 1
  - name: step 2
    node: docker-client
    step:
      type: simulated
      options:
        time: 2
        message: installing fake package 2
  - name: step 3
    node: docker-client
    step:
      type: simulated
      options:
        time: 2
        message: installing fake package 3

# Define the tests that will be executed
tests:
  - name: Hello World Test - Type 1
    node: docker-client
    execute: sleep 4 && echo "Hello World"
    check:
      match: "Hello World"
  - name: Hello World Test - Type 2
    node: docker-client
    execute: sleep 5 && echo "Hello World" | grep "Hello World"
    check:
      exit_code: 0
  - name: Hello World Test - Multiple Checks
    node: docker-client
    execute: sleep 3 && echo "Hello World"
    check:
      match: "Hello World"
      exit_code: 0
  - name: Hello World Failure Test
    node: docker-client
    execute: sleep 5 && echo "Hello Dork"
    check:
      match: "Hello World"