# Define the network that will be used in the test suite
networks:
  - name: test_net
    subnet: 192.168.200.0/24
    gateway: 192.168.200.1
# Define the images that will be used in the test suite
images:
  - name: test_server
    tag: latest
    dockerfile: dockerfiles/server.dockerfile
  - name: test_client
    tag: latest
    dockerfile: dockerfiles/client.dockerfile